version: '3.1'

services:
  db:
    build: ../images-dev/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: amtdb
      MYSQL_ROOT_PASSWORD: root
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - 8888:80 

volumes:
  dbdata:
